
version: '3'

services:
  user-service:
    build: ./backend/user-service
    ports:
      - "3001:3000"

  product-service:
    build: ./backend/product-service
    ports:
      - "3002:3000"

  order-service:
    build: ./backend/order-service
    ports:
      - "3003:3000"
